version: 2.1

parameters:
  environment:
    type: string
    default: "staging"
    enum: ["staging", "production"]
  
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build
          command: |
          echo "Build: << pipeline.parameters.environment >>"
  deploy:
    parameters:
      environment:
        type: string 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
          echo "Deploy: << parameters.environment >>"     


workflows:
 version: 2
 build_deploy:
   jobs:
     - build
     - deploy:
        environment: "production"
        filters:
          branches:
            only:
              - main
        requires:
          - build      
